### ISSUE TITLE
Stop oclif-CLI with an error when node version is not supported

### ISSUE THREAD

**Issue by tram98** [oclif/core#1197]
**Is your feature request related to a problem? Please describe.**
I installed the CLI globally using bun. I did not get an error during installation.
When I ran the app, I got an error `TypeError: shellPath.at is not a function`.
I noticed that I was running node 14 in my path, which is not supported.

**Describe the solution you'd like**
I suggest checking node's version at startup and fail with an error if the version is not supported.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mdonnalley** [comment]
We had a check for this at one point in time but [removed it](https://github.com/oclif/core/pull/762) because we thought it was unnecessary since `npm install` will fail when the `engine` property isn't satisfied.

I'm not super familiar with bun but it seems that `bun install` doesn't check the node `engine` property on install

**Comment by tram98** [comment]
Thanks for your work! I appreciate the effort 👏
