### ISSUE TITLE
Hooks: unable to stop command execution if error occurs

### ISSUE THREAD

**Issue by pviti** [oclif/core#393]
Executing `this.error()` or `this.exit()` inside an hook of any type (init, prerun ...) the terminal does not show any error message and the command is run ignoring the Error.

I've noticed this behavior after the migration from v1 to v2 and using the new package `@oclif/core`.
Is this a bug or has changed the way to interrupt command from inside hooks in case of errors?

Thanks!

**Comment by pviti** [comment]
To isolate the problem I've also tried to generate a new clean CLI with just a simple test command and a prerun hook, but still any Error inside the hook is ignored and the command is normally run without messages on the console

**Comment by mdonnalley** [comment]
@pviti Sorry for the delayed response.

We made the conscious decision to no longer allow hooks to exit the process so that hooks could be used to gather information across plugins. For example, I could have `my-cli list things` command that runs a hook to gather the `things` to list from all the installed plugins. In that scenario I wouldn't want one failed hook to exit the entire process.

That being said, the [runHook method](https://github.com/oclif/core/blob/44adb4d387695548a017b38249b0bc3453aedbdf/src/config/config.ts#L249) now returns the successes and failures from the hook execution. So it is still possible to exit the process based on the result of the hook execution
