### ISSUE TITLE
Table filter to allow expressions

### ISSUE THREAD

**Issue by gkman** [oclif/core#451]
**Is your feature request related to a problem? Please describe.**

I'm just getting started with `oclif` and am already really enjoying it. However I find myself wanting more. Specifically I like the filter flag for the table, but don't seem to be able filter on anything other than a string contains. I looked at the source code for this, but I am also new to `TypeScript` so, while I'm not 100% sure I'm not just making a mistake, I don't think the code has this capability, and at the moment it's probably a little over my head to make the PR for this functionality myself.

**Describe the solution you'd like**

```bash
$ my-cli command --filter "forks>=1"
Name              Forks
 ───────────────── ─────
 gene-actions-test 1
 gene-test         2
```

**Describe alternatives you've considered**

I haven't found anything else at the moment. I could always preprocess that content, but in my mind defeats the purpose of having these handy flags.

**Additional context**

none

**Comment by RodEsp** [comment]
Hi @gkman, you're right that the `--filter` flag for the table only allows filtering on strings, more specifically though, it [allows filtering using any valid regex](https://github.com/oclif/core/blob/f759fb1710eb1013a48fa04e817d43231553590a/src/cli-ux/styled/table.ts#L74). While this doesn't let you use mathematical functions you _can_ create regexs that do a great-than match. Check out [this replit](https://replit.com/@RodEsp/oclif-Table-Advanced-Filtering?v=1#index.js) for an example.

I won't close this issue because this it _would_ be nice to be able to use mathematical operator with the `--filter` flag but I'm not sure we'll be able to get to it anytime soon.

**Comment by gkman** [comment]
Sorry for the delay, was out on vacation. You know it didn't even dawn on me to just use the regex. Sorry about that, that is a totally viable solution to me. I don't see any real *need* for this feature then, but yes it ~would~ be very nice.
