### ISSUE TITLE
Flags.string execute a default function twice if the flag is not set.

### ISSUE THREAD

**Issue by lorenzo-shape** [oclif/core#739]
**Describe the bug**
When setting the default value of a string flag as the result of executing a function, that function is run twice if the flag is not set by the user. While it's run once if the user sets a value. 

**To Reproduce**
Code example:
```
import { Command, Flags } from '@oclif/core'

export async function defaultFoo(): Promise<string> {
  console.log('default foo!')
  return 'foo'
}

export default class TestCommand extends Command {

  static override flags = {
    foo: Flags.string({
      default: () => defaultFoo()
    }),
  }

  async run(): Promise<void> {
     const {flags} = await this.parse(TestCommand)
     this.log(flags.foo)
  }
}
```

**Expected behavior**
I would expect the defaultFoo() function to run only once when no value is passed by the user to the `--foo` flag, while it shouldn't run at all if the value of `--foo` is set by the user.

**Screenshots**
<img width="612" alt="Screenshot 2023-07-20 at 09 56 05" src="https://github.com/oclif/core/assets/107032340/ef193093-aafe-4797-928d-6b1c528dd033">

**Environment:**
 - OS & version: MacOS Ventura (Version 13.2.1)
 - @oclif/core: 2.8.0

**Comment by mdonnalley** [comment]
@lorenzo-shape Thanks for the creating this issue!

This is actually working as designed. The first call to `default` that you're observing is happening when the manifest[1] is being generated. Since you're working in a dev environment there is no cached manifest and so it will generate it at the beginning of every command execution. In a production environment, however, that manifest will be cached which means that it'll bypass that step, meaning that you won't have any duplicative calls to `default`

So in a production environment with a cached manifest, there will only be a single call to `default` when no value is provided. 

[1]The manifest is essentially a cache of all the commands with information like flag names, flag defaults, help description, etc... The intent of the manifest is to speed up performance in a production environment.

**Comment by lorenzo-shape** [comment]
@mdonnalley oh ok, thanks!
