### ISSUE TITLE
Arg summary missing in help text

### ISSUE THREAD

**Issue by cristiand391** [oclif/core#782]
**Describe the bug**
When defining an arg summary it doesn' show up in help text

**To Reproduce**
1. Clone https://github.com/cristiand391/sf-plugin-api
2. Change `description` to `summary` here: https://github.com/cristiand391/sf-plugin-api/blob/11387c27ddf12f8598ba00fcbf29e3da5fd99ff1/src/commands/org/api.ts#L65
3. run `./bin/dev org api --help`

with `description`:
<img width="1622" alt="Screenshot 2023-09-12 at 10 08 41" src="https://github.com/oclif/core/assets/6853656/dad21b14-5aa8-457f-8bde-0f1d36583968">

with `summary`:
<img width="1615" alt="Screenshot 2023-09-12 at 10 09 00" src="https://github.com/oclif/core/assets/6853656/4069810c-f6b6-455e-b132-0679c9a3fa8b">

**Expected behavior**
`summary` should work, like it does in flags.

**Environment (please complete the following information):**
 - OS & version: macos ventura
 - Shell/terminal & version: zsh/alacritty

**Comment by AllanOricil** [comment]
@cristiand391 this does not seem to be a bug because `ArgProps` do not have a `summary` attribute

https://github.com/oclif/core/blob/e61105f08c0450bf3a79a6ed7214e5eb14b339ac/src/interfaces/parser.ts#L175-L199

<img width="845" alt="image" src="https://github.com/oclif/core/assets/55927613/8eac9f16-7866-43f9-a9cd-b2b3f766a9f2">
