### ISSUE TITLE
files attribute must be specified check

### ISSUE THREAD

**Issue by moltar** [oclif/core#851]
Trying to understand what is the rationale for this check.

https://github.com/oclif/core/blob/6062edf9bb2abc738e71c73b3bd246c7a05357cf/src/config/plugin.ts#L173

I think it is valid to have no `files`, and it is possible to craft `.npmignore` in a way that will provide the same functionality in the end.

Is there any particular reason Oclif needs `files` to be set?

**Comment by mdonnalley** [comment]
That check was added way back in 2018: https://github.com/oclif/config/commit/cc73cb51da6a2d5c49e414107aef44b0830bb78d

Unfortunately, I'm not sure why it was added. I agree with you that it seems unnecessary, especially since it can be replaced with `.npmignore`. Feel free to open a PR if you would like to remove it

**Comment by moltar** [comment]
I opened a PR, but it requires CLA, which also requires to auth GH to Salesforce.

Just not something I am interested in at the moment.

Feel free to just use the PR/commit. I thereby grant full permission to that change 😁

**Comment by mdonnalley** [comment]
Thanks @moltar - I merged into another open PR which I plan to merge in the next day or so. Thanks for the contribution 🏆
