### ISSUE TITLE
[BUG] exclusive flag option doesn't work with negated flag (allowNo)

### ISSUE THREAD

**Issue by moritzraho** [oclif/core#940]
### Flags config

```
watermelon: flags.boolean({ default: true, allowNo: true }),
apple: flags.string({ exclusive: ['no-watermelon'] })
```

### Execution
```
> cmd --no-watermelon --apple
[executes]
```

## Expected Behavior

```
> cmd --no-watermelon --apple
Error: --apple= cannot also be provided when using --no-watermelon=
```

**Comment by mdonnalley** [comment]
I'm going to close this since I believe that it's working as designed and that using `relationships` is the right way to accomplish this.

Setting `exclusive` to the actual flag name (`watermelon`) will cause the validation error to throw for both `--no-watermelon` and `--watermelon`. 
```
watermelon: flags.boolean({ default: true, allowNo: true }),
apple: flags.string({ exclusive: ['watermelon'] })
```

If you want exclusivity based on a flag's value, then `relationships` is the way to go
